# Generated by Django 4.2 on 2023-04-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('singer', models.CharField(max_length=200, verbose_name='가수')),
                ('is_high', models.BooleanField(default=False, verbose_name='고음여부')),
                ('ctime', models.DateField(verbose_name='최초 추가 일시')),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_date', models.DateField()),
                ('songs', models.ManyToManyField(to='suna.song')),
            ],
        ),
    ]
